### ISSUE TITLE
Add project folder and ipynb file

### ISSUE THREAD

**Issue by elliotttrio** [QMSS-GR5069-Spring-2022/gr5069-homework-2-zhuyijie25#2]
It will be easier to find the file if we have a project folder. Also, please add the .ipynb version of your .html document.  Otherwise, I will have to convert your .html file.

**Comment by zhuyijie25** [comment]
Hi Elliot,

I have added a new one with ipynb file

**Comment by elliotttrio** [comment]
Hi Jackie, I'm working off of the development branch so please merge my changes and add the ipynb. I also messaged you on Slack if that makes it at all easier!

**Comment by zhuyijie25** [comment]
sure
